### PR TITLE
add contact-form

### PR DESCRIPTION
**Pull request by Agastya18**
# Description

add contact form for the /contact route

Fixes Issue #274

## Type of change

- New feature
- Feature Enhancement

# Demo:

Screenshot 2024-12-12 at 11 11 50 PM

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code

### CODE REVIEW

**Comment by raspberri05** [comment]
Thanks for opening a pull request. Your pull request will be reviewed soon!

**Review by raspberri05 — CHANGES_REQUESTED** [review]
Looks like the build had an error
image

After making the fixes you can also try building it locally with `npm run build` to see if the build errors were fixed. Also, what is the purpose of the Toaster component for?

**Comment by Agastya18** [comment]
toaster for simple feedback to users in the form

**Review by raspberri05 — APPROVED** [review]
Your pull request has been approved and will be merged shortly. Thanks for your contribution!
Please also consider starring this repository if you haven't already to allow more open source contributors to find this project.

**Pull request merged**
